version: '3.7'

services:
  jive:
    image: imlunahey/jive:latest
    build: .
    container_name: jive
    hostname: jive
    restart: always
    env_file: .env
    environment:
      - BOT_TOKEN=$BOT_TOKEN
